# Generated by Django 3.2.5 on 2021-08-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/profile_pics/default.jpg', null=True, upload_to='users/profile_pics'),
        ),
    ]
