# Generated by Django 3.2.5 on 2021-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210731_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='projects/thumbnails/thumbnail.png', null=True, upload_to='projects/thumbnails'),
        ),
    ]
