# Generated by Django 3.2.5 on 2021-08-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
