# Generated by Django 3.2.5 on 2021-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_category_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/thumbnails/thumbnail.png', upload_to='blog/thumbnails'),
        ),
    ]
