# Generated by Django 3.2.5 on 2021-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='blog/thumbnails/thumbnail.png', null=True, upload_to='blog/thumbnails'),
        ),
    ]
