# Generated by Django 3.2.5 on 2021-08-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['is_read', '-created']},
        ),
    ]
